In [11]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

In [12]:
import random
from sklearn.model_selection import cross_val_score

In [13]:
intent_queries = {
"TOTAL_SALES": [
"Show me total sales", "What is overall revenue?", "How much did we sell in total?",
"Give me total earnings", "Calculate all sales", "What’s the total profit?",
"Display complete sales amount", "Revenue overall", "Sum of all sales",
"Give me sales summary", "How much did we earn?", "Total revenue please",
"Show overall turnover", "Total income of company", "What’s our gross sales?",
"Provide overall sales data", "What’s the total amount sold?", "Show me combined sales",
"Give me total revenue numbers", "Summarize all sales"
],
"TREND_MONTH": [
"Show me monthly sales trend", "Sales growth by month", "How sales changed month to month?",
"Plot monthly revenue trend", "Monthly trend of profits", "Compare months by sales",
"What is the trend in last months?", "Revenue variation each month", "Month wise performance",
"How are monthly earnings moving?", "Trend of sales per month", "Give line chart of month sales",
"Growth over months", "Month to month sales data", "Monthly increase or decrease",
"Track sales over months", "Which month performed best?", "Show changes month-wise",
"Graph of sales by months", "Month trend report"
],
"FILTER_REGION": [
"Show sales in North region", "Sales only for East region", "Give revenue for South",
"Filter data by region", "Show me sales for West zone", "Revenue in North only",
"Sales figures for East zone", "Region-specific performance", "Profit in South",
"Display West region results", "North zone report", "East zone revenue", "South area sales",
"Give me region-wise breakdown", "Region wise report of sales",
"Revenue from South zone", "What’s North region profit?", "Data for East only",
"Show only South sales", "Filter to West region"
],
"AVG_PROFIT_YEAR": [
"Show average yearly profit", "What is avg profit each year?", "Year wise average earnings",
"Calculate annual profit average", "Year average revenue", "How much on average per year?",
"Yearly avg turnover", "Give average of yearly sales", "Profit average by year",
"Display avg revenue per year", "Annual mean profit", "Avg sales in a year",
"What’s the yearly average income?", "Revenue average each year", "Year avg growth",
"Year-wise avg profit trend", "Calculate yearly averages", "Give mean of yearly profits",
"Show avg earning trend annually", "Summarize average profit per year"
],
"AGGREGATE_REGION": [
"Summarize sales by region", "Aggregate revenue across regions", "Group sales by zone",
"Show me sales total by area", "Region wise aggregation of sales", "Breakdown by regions",
"Revenue grouped per region", "Profit aggregated by region", "Regional totals of sales",
"Display sales grouped by geography", "Zone wise aggregation", "Combine sales by region",
"Total sales each region", "Overall sales grouped regionally", "Show aggregated numbers per region",
"Sales by territory", "Sum grouped by area", "Aggregate by regional divisions",
"Revenue distribution per region", "Summarize zones by sales"
],
"TOP_PRODUCTS": [
"Show top selling products", "Which product sold the most?", "Give me best performing items",
"Top 5 products by sales", "Highest revenue items", "Most popular products",
"List top 10 items", "Best sellers report", "Which products are trending?",
"Show products with highest profit", "Popular products list", "Top revenue generating items",
"Best 3 products by sales", "Highest demand items", "Show me the hot products",
"Top performers in sales", "Which item is best selling?", "Products with max sales",
"Best selling products overall", "Top sales products chart"
]
}

In [14]:
queries, labels = [], []
for label, qs in intent_queries.items():
    for q in qs:
        queries.append(q)
        labels.append(label)


# Create DataFrame
data = pd.DataFrame({"query": queries, "intent": labels})
print("Dataset size:", data.shape)

Dataset size: (120, 2)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(data["query"], data["intent"],
test_size=0.2, random_state=42, stratify=data["intent"])

In [16]:
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)


clf = LogisticRegression(max_iter=1000)
clf.fit(X_train_vec, y_train)

LogisticRegression(max_iter=1000)

In [17]:
y_pred = clf.predict(X_test_vec)
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.875

Classification Report:
                   precision    recall  f1-score   support

AGGREGATE_REGION       0.67      0.50      0.57         4
 AVG_PROFIT_YEAR       1.00      1.00      1.00         4
   FILTER_REGION       0.60      0.75      0.67         4
    TOP_PRODUCTS       1.00      1.00      1.00         4
     TOTAL_SALES       1.00      1.00      1.00         4
     TREND_MONTH       1.00      1.00      1.00         4

        accuracy                           0.88        24
       macro avg       0.88      0.88      0.87        24
    weighted avg       0.88      0.88      0.87        24

In [18]:
scores = cross_val_score(clf, vectorizer.transform(data["query"]), data["intent"], cv=5)
print("\nCross-validation Accuracy (5-fold):", scores.mean())

Cross-validation Accuracy (5-fold): 0.925

In [19]:
def predict_with_confidence(user_query, threshold=0.5):
    vec = vectorizer.transform([user_query])
    probs = clf.predict_proba(vec).max()
    label = clf.predict(vec)[0]
    if probs < threshold:
        return "I didn’t understand, please rephrase."
    else:
        return label

In [20]:
# You can reuse your expanded dataset dict; add a few synonyms for robustness
intent_queries = {
    "TOTAL_SALES": [
        "Show me total sales","What is overall revenue?","How much did we sell in total?",
        "Give me total earnings","Calculate all sales","Sum of all sales","Total revenue please",
        "Overall turnover","Total income of company","Combined sales amount","Gross sales overall",
        "How much revenue did we make?"
    ],
    "TREND_MONTH": [
        "Show monthly sales trend","Sales growth by month","Plot monthly revenue trend",
        "Monthly trend of profits","Month wise performance","Line chart of month sales",
        "Month-to-month sales changes","Which month performed best?"
    ],
    "FILTER_REGION": [
        "Show sales in North region","Sales only for East region","Revenue for South region",
        "Profit in West region","Filter to North zone","East zone revenue","South area sales",
        "West region performance"
    ],
    "AVG_PROFIT_YEAR": [
        "Average profit in 2023","Show average yearly profit","Annual mean profit",
        "Year-wise average earnings","Avg sales in a year","Average revenue per year",
        "Yearly average profit"
    ],
    "AGGREGATE_REGION": [
        "Summarize sales by region","Total sales each region","Group sales by region",
        "Revenue grouped per region","Region wise aggregation of sales","Regional sales totals"
    ],
    "TOP_PRODUCTS": [
        "Top 5 products by sales","Which product sold the most?","Best selling products",
        "Highest revenue items","Popular products list","Top revenue generating items"
    ]
}

# Flatten to a DataFrame
rows = []
for intent, qs in intent_queries.items():
    for q in qs:
        rows.append({"query": q, "intent": intent})
train_df = pd.DataFrame(rows)
print("Training samples:", len(train_df))
train_df.sample(5)

Training samples: 47

                       query            intent
34     Yearly average profit   AVG_PROFIT_YEAR
36   Total sales each region  AGGREGATE_REGION
3     Give me total earnings       TOTAL_SALES
26          South area sales     FILTER_REGION
12  Show monthly sales trend       TREND_MONTH

In [22]:
!pip install -q sentence-transformers

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
!pip install protobuf==3.20.3

Collecting protobuf==3.20.3
  Downloading protobuf-3.20.3-cp310-cp310-win_amd64.whl.metadata (698 bytes)
Downloading protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
   ---------------------------------------- 0.0/904.0 kB ? eta -:--:--
   ---------------------------------------- 904.0/904.0 kB 4.6 MB/s eta 0:00:00
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.31.1
    Uninstalling protobuf-6.31.1:
      Successfully uninstalled protobuf-6.31.1
Successfully installed protobuf-3.20.3

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\DELL\AppData\Local\Programs\Python\Python310\Lib\site-packages\google\~-pb'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.
tensorflow 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
!pip uninstall -y sentence-transformers
!pip install sentence-transformers==2.2.2

Found existing installation: sentence-transformers 5.1.0
Uninstalling sentence-transformers-5.1.0:
  Successfully uninstalled sentence-transformers-5.1.0
Collecting sentence-transformers==2.2.2
  Downloading sentence-transformers-2.2.2.tar.gz (85 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers==2.2.2) (4.53.3)
Requirement already satisfied: tqdm in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers==2.2.2) (4.67.1)
Requirement already satisfied: torch>=1.6.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers==2.2.2) (2.7.1)
Collecting torchvision (from sentence-transformers==2.2.2)
  Downloading torchvision-0.23.0-cp310-cp310-win_amd64.whl.metadata (6.1 kB)
Requirement already satisfied: numpy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers==2.2.2) (2.2.6)
Requirement already satisfied: scikit-learn in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers==2.2.2) (1.7.0)
Requirement already satisfied: scipy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers==2.2.2) (1.15.3)
Requirement already satisfied: nltk in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers==2.2.2) (3.9.1)
Collecting sentencepiece (from sentence-transformers==2.2.2)
  Downloading sentencepiece-0.2.1-cp310-cp310-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: huggingface-hub>=0.4.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers==2.2.2) (0.33.4)
Requirement already satisfied: filelock in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (3.18.0)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (2024.11.6)
Requirement already satisfied: requests in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.4.0->sentence-transformers==2.2.2) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.4.0->sentence-transformers==2.2.2) (4.14.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (1.14.0)
Requirement already satisfied: networkx in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sympy>=1.13.3->torch>=1.6.0->sentence-transformers==2.2.2) (1.3.0)
Requirement already satisfied: colorama in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from tqdm->sentence-transformers==2.2.2) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch>=1.6.0->sentence-transformers==2.2.2) (3.0.2)
Requirement already satisfied: click in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from nltk->sentence-transformers==2.2.2) (8.2.1)
Requirement already satisfied: joblib in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from nltk->sentence-transformers==2.2.2) (1.5.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2) (2025.7.14)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sentence-transformers==2.2.2) (3.6.0)
Collecting torch>=1.6.0 (from sentence-transformers==2.2.2)
  Downloading torch-2.8.0-cp310-cp310-win_amd64.whl.metadata (30 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torchvision->sentence-transformers==2.2.2) (11.3.0)
Downloading sentencepiece-0.2.1-cp310-cp310-win_amd64.whl (1.1 MB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 1.1/1.1 MB 6.3 MB/s eta 0:00:00
Downloading torchvision-0.23.0-cp310-cp310-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------------------- -------------------- 0.8/1.6 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 3.6 MB/s eta 0:00:00
Downloading torch-2.8.0-cp310-cp310-win_amd64.whl (241.4 MB)
   ---------------------------------------- 0.0/241.4 MB ? eta -:--:--
   ---------------------------------------- 0.8/241.4 MB 3.7 MB/s eta 0:01:05
   ---------------------------------------- 1.6/241.4 MB 4.0 MB/s eta 0:01:01
   ---------------------------------------- 2.4/241.4 MB 3.8 MB/s eta 0:01:03
    --------------------------------------- 3.1/241.4 MB 3.9 MB/s eta 0:01:01
    --------------------------------------- 3.9/241.4 MB 3.9 MB/s eta 0:01:02
    --------------------------------------- 4.2/241.4 MB 3.4 MB/s eta 0:01:09
    --------------------------------------- 4.5/241.4 MB 3.3 MB/s eta 0:01:12
    --------------------------------------- 5.2/241.4 MB 3.1 MB/s eta 0:01:18
    --------------------------------------- 5.8/241.4 MB 3.0 MB/s eta 0:01:18
   - -------------------------------------- 6.6/241.4 MB 3.1 MB/s eta 0:01:16
   - -------------------------------------- 7.3/241.4 MB 3.2 MB/s eta 0:01:14
   - -------------------------------------- 8.1/241.4 MB 3.2 MB/s eta 0:01:12
   - -------------------------------------- 8.9/241.4 MB 3.3 MB/s eta 0:01:11
   - -------------------------------------- 9.7/241.4 MB 3.3 MB/s eta 0:01:10
   - -------------------------------------- 10.5/241.4 MB 3.4 MB/s eta 0:01:09
   - -------------------------------------- 11.3/241.4 MB 3.4 MB/s eta 0:01:08
   - -------------------------------------- 12.1/241.4 MB 3.4 MB/s eta 0:01:07
   -- ------------------------------------- 13.1/241.4 MB 3.5 MB/s eta 0:01:06
   -- ------------------------------------- 13.9/241.4 MB 3.5 MB/s eta 0:01:06
   -- ------------------------------------- 14.7/241.4 MB 3.5 MB/s eta 0:01:05
   -- ------------------------------------- 15.5/241.4 MB 3.5 MB/s eta 0:01:04
   -- ------------------------------------- 16.3/241.4 MB 3.5 MB/s eta 0:01:04
   -- ------------------------------------- 17.0/241.4 MB 3.6 MB/s eta 0:01:03
   -- ------------------------------------- 17.8/241.4 MB 3.6 MB/s eta 0:01:03
   --- ------------------------------------ 18.4/241.4 MB 3.5 MB/s eta 0:01:04
   --- ------------------------------------ 18.9/241.4 MB 3.5 MB/s eta 0:01:04
   --- ------------------------------------ 19.4/241.4 MB 3.4 MB/s eta 0:01:05
   --- ------------------------------------ 19.7/241.4 MB 3.4 MB/s eta 0:01:05
   --- ------------------------------------ 20.2/241.4 MB 3.4 MB/s eta 0:01:06
   --- ------------------------------------ 21.0/241.4 MB 3.4 MB/s eta 0:01:06
   --- ------------------------------------ 21.8/241.4 MB 3.4 MB/s eta 0:01:05
   --- ------------------------------------ 22.5/241.4 MB 3.4 MB/s eta 0:01:05
   --- ------------------------------------ 23.3/241.4 MB 3.4 MB/s eta 0:01:04
   --- ------------------------------------ 24.1/241.4 MB 3.4 MB/s eta 0:01:04
   ---- ----------------------------------- 24.9/241.4 MB 3.4 MB/s eta 0:01:04
   ---- ----------------------------------- 25.7/241.4 MB 3.4 MB/s eta 0:01:03
   ---- ----------------------------------- 26.5/241.4 MB 3.5 MB/s eta 0:01:03
   ---- ----------------------------------- 27.3/241.4 MB 3.5 MB/s eta 0:01:02
   ---- ----------------------------------- 28.0/241.4 MB 3.5 MB/s eta 0:01:02
   ---- ----------------------------------- 28.8/241.4 MB 3.5 MB/s eta 0:01:01
   ---- ----------------------------------- 29.6/241.4 MB 3.5 MB/s eta 0:01:01
   ----- ---------------------------------- 30.4/241.4 MB 3.5 MB/s eta 0:01:01
   ----- ---------------------------------- 31.2/241.4 MB 3.5 MB/s eta 0:01:00
   ----- ---------------------------------- 32.0/241.4 MB 3.5 MB/s eta 0:01:00
   ----- ---------------------------------- 32.5/241.4 MB 3.5 MB/s eta 0:01:00
   ----- ---------------------------------- 33.3/241.4 MB 3.5 MB/s eta 0:01:00
   ----- ---------------------------------- 33.8/241.4 MB 3.5 MB/s eta 0:01:00
   ----- ---------------------------------- 34.3/241.4 MB 3.5 MB/s eta 0:01:00
   ----- ---------------------------------- 34.9/241.4 MB 3.5 MB/s eta 0:01:00
   ----- ---------------------------------- 35.7/241.4 MB 3.4 MB/s eta 0:01:00
   ----- ---------------------------------- 36.2/241.4 MB 3.4 MB/s eta 0:01:00
   ------ --------------------------------- 37.0/241.4 MB 3.4 MB/s eta 0:01:00
   ------ --------------------------------- 37.7/241.4 MB 3.4 MB/s eta 0:01:00
   ------ --------------------------------- 38.5/241.4 MB 3.4 MB/s eta 0:00:59
   ------ --------------------------------- 39.3/241.4 MB 3.5 MB/s eta 0:00:59
   ------ --------------------------------- 40.1/241.4 MB 3.5 MB/s eta 0:00:59
   ------ --------------------------------- 40.9/241.4 MB 3.5 MB/s eta 0:00:58
   ------ --------------------------------- 41.7/241.4 MB 3.5 MB/s eta 0:00:58
   ------- -------------------------------- 42.5/241.4 MB 3.5 MB/s eta 0:00:57
   ------- -------------------------------- 43.3/241.4 MB 3.5 MB/s eta 0:00:57
   ------- -------------------------------- 44.0/241.4 MB 3.5 MB/s eta 0:00:57
   ------- -------------------------------- 44.8/241.4 MB 3.5 MB/s eta 0:00:57
   ------- -------------------------------- 45.6/241.4 MB 3.5 MB/s eta 0:00:56
   ------- -------------------------------- 46.4/241.4 MB 3.5 MB/s eta 0:00:56
   ------- -------------------------------- 47.2/241.4 MB 3.5 MB/s eta 0:00:56
   ------- -------------------------------- 47.7/241.4 MB 3.5 MB/s eta 0:00:56
   -------- ------------------------------- 48.5/241.4 MB 3.5 MB/s eta 0:00:56
   -------- ------------------------------- 49.3/241.4 MB 3.5 MB/s eta 0:00:55
   -------- ------------------------------- 50.1/241.4 MB 3.5 MB/s eta 0:00:55
   -------- ------------------------------- 50.6/241.4 MB 3.5 MB/s eta 0:00:55
   -------- ------------------------------- 51.4/241.4 MB 3.5 MB/s eta 0:00:55
   -------- ------------------------------- 52.2/241.4 MB 3.5 MB/s eta 0:00:55
   -------- ------------------------------- 53.0/241.4 MB 3.5 MB/s eta 0:00:54
   -------- ------------------------------- 53.7/241.4 MB 3.5 MB/s eta 0:00:54
   --------- ------------------------------ 54.5/241.4 MB 3.5 MB/s eta 0:00:54
   --------- ------------------------------ 55.3/241.4 MB 3.5 MB/s eta 0:00:53
   --------- ------------------------------ 56.1/241.4 MB 3.5 MB/s eta 0:00:53
   --------- ------------------------------ 57.1/241.4 MB 3.5 MB/s eta 0:00:53
   --------- ------------------------------ 57.9/241.4 MB 3.5 MB/s eta 0:00:53
   --------- ------------------------------ 58.5/241.4 MB 3.5 MB/s eta 0:00:52
   --------- ------------------------------ 59.2/241.4 MB 3.5 MB/s eta 0:00:52
   --------- ------------------------------ 60.0/241.4 MB 3.5 MB/s eta 0:00:52
   ---------- ----------------------------- 60.8/241.4 MB 3.5 MB/s eta 0:00:52
   ---------- ----------------------------- 61.3/241.4 MB 3.5 MB/s eta 0:00:52
   ---------- ----------------------------- 62.1/241.4 MB 3.5 MB/s eta 0:00:51
   ---------- ----------------------------- 62.9/241.4 MB 3.5 MB/s eta 0:00:51
   ---------- ----------------------------- 63.7/241.4 MB 3.5 MB/s eta 0:00:51
   ---------- ----------------------------- 64.5/241.4 MB 3.5 MB/s eta 0:00:51
   ---------- ----------------------------- 65.3/241.4 MB 3.5 MB/s eta 0:00:50
   ---------- ----------------------------- 66.1/241.4 MB 3.5 MB/s eta 0:00:50
   ----------- ---------------------------- 66.8/241.4 MB 3.5 MB/s eta 0:00:50
   ----------- ---------------------------- 67.6/241.4 MB 3.5 MB/s eta 0:00:50
   ----------- ---------------------------- 68.4/241.4 MB 3.5 MB/s eta 0:00:49
   ----------- ---------------------------- 69.2/241.4 MB 3.5 MB/s eta 0:00:49
   ----------- ---------------------------- 70.0/241.4 MB 3.5 MB/s eta 0:00:49
   ----------- ---------------------------- 70.8/241.4 MB 3.5 MB/s eta 0:00:49
   ----------- ---------------------------- 71.6/241.4 MB 3.6 MB/s eta 0:00:48
   ----------- ---------------------------- 72.4/241.4 MB 3.6 MB/s eta 0:00:48
   ------------ --------------------------- 73.1/241.4 MB 3.6 MB/s eta 0:00:48
   ------------ --------------------------- 73.9/241.4 MB 3.6 MB/s eta 0:00:48
   ------------ --------------------------- 74.7/241.4 MB 3.6 MB/s eta 0:00:47
   ------------ --------------------------- 75.5/241.4 MB 3.6 MB/s eta 0:00:47
   ------------ --------------------------- 76.3/241.4 MB 3.6 MB/s eta 0:00:47
   ------------ --------------------------- 76.8/241.4 MB 3.6 MB/s eta 0:00:47
   ------------ --------------------------- 77.6/241.4 MB 3.6 MB/s eta 0:00:46
   ------------ --------------------------- 78.4/241.4 MB 3.6 MB/s eta 0:00:46
   ------------- -------------------------- 79.2/241.4 MB 3.6 MB/s eta 0:00:46
   ------------- -------------------------- 80.0/241.4 MB 3.6 MB/s eta 0:00:46
   ------------- -------------------------- 80.7/241.4 MB 3.6 MB/s eta 0:00:46
   ------------- -------------------------- 81.5/241.4 MB 3.6 MB/s eta 0:00:45
   ------------- -------------------------- 82.3/241.4 MB 3.6 MB/s eta 0:00:45
   ------------- -------------------------- 83.1/241.4 MB 3.6 MB/s eta 0:00:45
   ------------- -------------------------- 83.9/241.4 MB 3.6 MB/s eta 0:00:45
   -------------- ------------------------- 84.7/241.4 MB 3.6 MB/s eta 0:00:44
   -------------- ------------------------- 85.5/241.4 MB 3.6 MB/s eta 0:00:44
   -------------- ------------------------- 86.2/241.4 MB 3.6 MB/s eta 0:00:44
   -------------- ------------------------- 87.0/241.4 MB 3.6 MB/s eta 0:00:44
   -------------- ------------------------- 87.8/241.4 MB 3.6 MB/s eta 0:00:43
   -------------- ------------------------- 88.6/241.4 MB 3.6 MB/s eta 0:00:43
   -------------- ------------------------- 89.4/241.4 MB 3.6 MB/s eta 0:00:43
   -------------- ------------------------- 90.2/241.4 MB 3.6 MB/s eta 0:00:43
   --------------- ------------------------ 91.0/241.4 MB 3.6 MB/s eta 0:00:42
   --------------- ------------------------ 91.8/241.4 MB 3.6 MB/s eta 0:00:42
   --------------- ------------------------ 92.5/241.4 MB 3.6 MB/s eta 0:00:42
   --------------- ------------------------ 93.3/241.4 MB 3.6 MB/s eta 0:00:42
   --------------- ------------------------ 94.1/241.4 MB 3.6 MB/s eta 0:00:41
   --------------- ------------------------ 94.9/241.4 MB 3.6 MB/s eta 0:00:41
   --------------- ------------------------ 95.7/241.4 MB 3.6 MB/s eta 0:00:41
   --------------- ------------------------ 96.5/241.4 MB 3.6 MB/s eta 0:00:41
   ---------------- ----------------------- 97.3/241.4 MB 3.6 MB/s eta 0:00:40
   ---------------- ----------------------- 98.0/241.4 MB 3.6 MB/s eta 0:00:40
   ---------------- ----------------------- 98.8/241.4 MB 3.6 MB/s eta 0:00:40
   ---------------- ----------------------- 99.6/241.4 MB 3.6 MB/s eta 0:00:40
   ---------------- ----------------------- 100.4/241.4 MB 3.6 MB/s eta 0:00:40
   ---------------- ----------------------- 101.2/241.4 MB 3.6 MB/s eta 0:00:39
   ---------------- ----------------------- 102.0/241.4 MB 3.6 MB/s eta 0:00:39
   ----------------- ---------------------- 102.8/241.4 MB 3.6 MB/s eta 0:00:39
   ----------------- ---------------------- 103.5/241.4 MB 3.6 MB/s eta 0:00:39
   ----------------- ---------------------- 104.3/241.4 MB 3.6 MB/s eta 0:00:38
   ----------------- ---------------------- 105.1/241.4 MB 3.6 MB/s eta 0:00:38
   ----------------- ---------------------- 105.9/241.4 MB 3.6 MB/s eta 0:00:38
   ----------------- ---------------------- 106.7/241.4 MB 3.6 MB/s eta 0:00:38
   ----------------- ---------------------- 107.2/241.4 MB 3.6 MB/s eta 0:00:38
   ----------------- ---------------------- 108.5/241.4 MB 3.6 MB/s eta 0:00:37
   ------------------ --------------------- 109.3/241.4 MB 3.6 MB/s eta 0:00:37
   ------------------ --------------------- 110.1/241.4 MB 3.6 MB/s eta 0:00:37
   ------------------ --------------------- 110.9/241.4 MB 3.6 MB/s eta 0:00:36
   ------------------ --------------------- 111.7/241.4 MB 3.6 MB/s eta 0:00:36
   ------------------ --------------------- 112.5/241.4 MB 3.6 MB/s eta 0:00:36
   ------------------ --------------------- 113.2/241.4 MB 3.6 MB/s eta 0:00:36
   ------------------ --------------------- 114.0/241.4 MB 3.7 MB/s eta 0:00:35
   ------------------- -------------------- 114.8/241.4 MB 3.7 MB/s eta 0:00:35
   ------------------- -------------------- 115.6/241.4 MB 3.7 MB/s eta 0:00:35
   ------------------- -------------------- 116.4/241.4 MB 3.7 MB/s eta 0:00:35
   ------------------- -------------------- 117.2/241.4 MB 3.7 MB/s eta 0:00:34
   ------------------- -------------------- 118.0/241.4 MB 3.7 MB/s eta 0:00:34
   ------------------- -------------------- 118.8/241.4 MB 3.7 MB/s eta 0:00:34
   ------------------- -------------------- 119.5/241.4 MB 3.7 MB/s eta 0:00:34
   ------------------- -------------------- 120.3/241.4 MB 3.7 MB/s eta 0:00:33
   -------------------- ------------------- 121.1/241.4 MB 3.7 MB/s eta 0:00:33
   -------------------- ------------------- 121.9/241.4 MB 3.7 MB/s eta 0:00:33
   -------------------- ------------------- 122.7/241.4 MB 3.7 MB/s eta 0:00:33
   -------------------- ------------------- 123.5/241.4 MB 3.7 MB/s eta 0:00:33

  DEPRECATION: Building 'sentence-transformers' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'sentence-transformers'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\DELL\AppData\Local\Programs\Python\Python310\Lib\site-packages\~orch'.
  You can safely remove it manually.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
!pip install torch==2.1.0

Collecting torch==2.1.0
  Downloading torch-2.1.0-cp310-cp310-win_amd64.whl.metadata (24 kB)
Requirement already satisfied: filelock in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (3.18.0)
Requirement already satisfied: typing-extensions in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (4.14.1)
Requirement already satisfied: sympy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (1.14.0)
Requirement already satisfied: networkx in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (3.1.6)
Requirement already satisfied: fsspec in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (2025.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch==2.1.0) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch==2.1.0) (1.3.0)
Downloading torch-2.1.0-cp310-cp310-win_amd64.whl (192.3 MB)
   ---------------------------------------- 0.0/192.3 MB ? eta -:--:--
   ---------------------------------------- 1.0/192.3 MB 6.3 MB/s eta 0:00:31
   ---------------------------------------- 1.8/192.3 MB 4.6 MB/s eta 0:00:42
    --------------------------------------- 2.6/192.3 MB 4.3 MB/s eta 0:00:44
    --------------------------------------- 3.4/192.3 MB 4.2 MB/s eta 0:00:46
    --------------------------------------- 4.5/192.3 MB 4.1 MB/s eta 0:00:47
   - -------------------------------------- 5.2/192.3 MB 4.0 MB/s eta 0:00:47
   - -------------------------------------- 6.0/192.3 MB 4.1 MB/s eta 0:00:46
   - -------------------------------------- 6.8/192.3 MB 4.1 MB/s eta 0:00:46
   - -------------------------------------- 7.6/192.3 MB 4.0 MB/s eta 0:00:47
   - -------------------------------------- 8.4/192.3 MB 4.0 MB/s eta 0:00:46
   - -------------------------------------- 9.2/192.3 MB 4.0 MB/s eta 0:00:46
   -- ------------------------------------- 10.0/192.3 MB 4.0 MB/s eta 0:00:46
   -- ------------------------------------- 11.0/192.3 MB 4.0 MB/s eta 0:00:46
   -- ------------------------------------- 11.8/192.3 MB 4.0 MB/s eta 0:00:46
   -- ------------------------------------- 12.6/192.3 MB 3.9 MB/s eta 0:00:46
   -- ------------------------------------- 13.4/192.3 MB 4.0 MB/s eta 0:00:46
   -- ------------------------------------- 14.2/192.3 MB 4.0 MB/s eta 0:00:46
   --- ------------------------------------ 14.9/192.3 MB 3.9 MB/s eta 0:00:45
   --- ------------------------------------ 15.7/192.3 MB 3.9 MB/s eta 0:00:45
   --- ------------------------------------ 16.3/192.3 MB 3.8 MB/s eta 0:00:46
   --- ------------------------------------ 16.5/192.3 MB 3.8 MB/s eta 0:00:47
   --- ------------------------------------ 17.0/192.3 MB 3.7 MB/s eta 0:00:48
   --- ------------------------------------ 17.8/192.3 MB 3.7 MB/s eta 0:00:48
   --- ------------------------------------ 18.4/192.3 MB 3.6 MB/s eta 0:00:48
   --- ------------------------------------ 19.1/192.3 MB 3.6 MB/s eta 0:00:48
   ---- ----------------------------------- 19.9/192.3 MB 3.7 MB/s eta 0:00:48
   ---- ----------------------------------- 20.7/192.3 MB 3.7 MB/s eta 0:00:47
   ---- ----------------------------------- 21.5/192.3 MB 3.7 MB/s eta 0:00:47
   ---- ----------------------------------- 22.5/192.3 MB 3.7 MB/s eta 0:00:47
   ---- ----------------------------------- 23.3/192.3 MB 3.7 MB/s eta 0:00:46
   ----- ---------------------------------- 24.1/192.3 MB 3.7 MB/s eta 0:00:46
   ----- ---------------------------------- 24.9/192.3 MB 3.7 MB/s eta 0:00:46
   ----- ---------------------------------- 25.7/192.3 MB 3.7 MB/s eta 0:00:46
   ----- ---------------------------------- 26.5/192.3 MB 3.7 MB/s eta 0:00:45
   ----- ---------------------------------- 27.3/192.3 MB 3.7 MB/s eta 0:00:45
   ----- ---------------------------------- 28.3/192.3 MB 3.7 MB/s eta 0:00:45
   ------ --------------------------------- 29.1/192.3 MB 3.7 MB/s eta 0:00:44
   ------ --------------------------------- 29.9/192.3 MB 3.7 MB/s eta 0:00:44
   ------ --------------------------------- 30.7/192.3 MB 3.7 MB/s eta 0:00:44
   ------ --------------------------------- 31.5/192.3 MB 3.7 MB/s eta 0:00:44
   ------ --------------------------------- 32.2/192.3 MB 3.7 MB/s eta 0:00:43
   ------ --------------------------------- 33.0/192.3 MB 3.7 MB/s eta 0:00:43
   ------- -------------------------------- 33.8/192.3 MB 3.7 MB/s eta 0:00:43
   ------- -------------------------------- 34.3/192.3 MB 3.7 MB/s eta 0:00:43
   ------- -------------------------------- 34.6/192.3 MB 3.7 MB/s eta 0:00:43
   ------- -------------------------------- 35.1/192.3 MB 3.6 MB/s eta 0:00:44
   ------- -------------------------------- 35.7/192.3 MB 3.6 MB/s eta 0:00:44
   ------- -------------------------------- 36.4/192.3 MB 3.6 MB/s eta 0:00:44
   ------- -------------------------------- 37.2/192.3 MB 3.6 MB/s eta 0:00:43
   ------- -------------------------------- 38.0/192.3 MB 3.6 MB/s eta 0:00:43
   -------- ------------------------------- 38.8/192.3 MB 3.6 MB/s eta 0:00:43
   -------- ------------------------------- 39.6/192.3 MB 3.6 MB/s eta 0:00:43
   -------- ------------------------------- 40.6/192.3 MB 3.6 MB/s eta 0:00:42
   -------- ------------------------------- 41.4/192.3 MB 3.6 MB/s eta 0:00:42
   -------- ------------------------------- 42.2/192.3 MB 3.6 MB/s eta 0:00:42
   -------- ------------------------------- 43.0/192.3 MB 3.6 MB/s eta 0:00:41
   --------- ------------------------------ 43.8/192.3 MB 3.7 MB/s eta 0:00:41
   --------- ------------------------------ 44.6/192.3 MB 3.7 MB/s eta 0:00:41
   --------- ------------------------------ 45.4/192.3 MB 3.7 MB/s eta 0:00:41
   --------- ------------------------------ 46.1/192.3 MB 3.7 MB/s eta 0:00:40
   --------- ------------------------------ 47.2/192.3 MB 3.7 MB/s eta 0:00:40
   --------- ------------------------------ 48.0/192.3 MB 3.7 MB/s eta 0:00:40
   ---------- ----------------------------- 48.8/192.3 MB 3.7 MB/s eta 0:00:40
   ---------- ----------------------------- 49.5/192.3 MB 3.7 MB/s eta 0:00:39
   ---------- ----------------------------- 50.3/192.3 MB 3.7 MB/s eta 0:00:39
   ---------- ----------------------------- 51.1/192.3 MB 3.7 MB/s eta 0:00:39
   ---------- ----------------------------- 51.9/192.3 MB 3.7 MB/s eta 0:00:39
   ---------- ----------------------------- 52.4/192.3 MB 3.7 MB/s eta 0:00:39
   ----------- ---------------------------- 53.0/192.3 MB 3.7 MB/s eta 0:00:39
   ----------- ---------------------------- 53.7/192.3 MB 3.6 MB/s eta 0:00:39
   ----------- ---------------------------- 54.3/192.3 MB 3.6 MB/s eta 0:00:39
   ----------- ---------------------------- 55.1/192.3 MB 3.6 MB/s eta 0:00:38
   ----------- ---------------------------- 55.8/192.3 MB 3.6 MB/s eta 0:00:38
   ----------- ---------------------------- 56.4/192.3 MB 3.6 MB/s eta 0:00:38
   ----------- ---------------------------- 56.9/192.3 MB 3.6 MB/s eta 0:00:38
   ----------- ---------------------------- 57.7/192.3 MB 3.6 MB/s eta 0:00:38
   ------------ --------------------------- 58.5/192.3 MB 3.6 MB/s eta 0:00:38
   ------------ --------------------------- 59.5/192.3 MB 3.6 MB/s eta 0:00:37
   ------------ --------------------------- 60.3/192.3 MB 3.6 MB/s eta 0:00:37
   ------------ --------------------------- 61.1/192.3 MB 3.6 MB/s eta 0:00:37
   ------------ --------------------------- 61.9/192.3 MB 3.6 MB/s eta 0:00:36
   ------------- -------------------------- 62.7/192.3 MB 3.6 MB/s eta 0:00:36
   ------------- -------------------------- 63.4/192.3 MB 3.6 MB/s eta 0:00:36
   ------------- -------------------------- 64.2/192.3 MB 3.6 MB/s eta 0:00:36
   ------------- -------------------------- 65.0/192.3 MB 3.6 MB/s eta 0:00:35
   ------------- -------------------------- 66.1/192.3 MB 3.6 MB/s eta 0:00:35
   ------------- -------------------------- 66.8/192.3 MB 3.6 MB/s eta 0:00:35
   -------------- ------------------------- 67.6/192.3 MB 3.6 MB/s eta 0:00:35
   -------------- ------------------------- 68.4/192.3 MB 3.7 MB/s eta 0:00:34
   -------------- ------------------------- 69.2/192.3 MB 3.6 MB/s eta 0:00:34
   -------------- ------------------------- 70.0/192.3 MB 3.7 MB/s eta 0:00:34
   -------------- ------------------------- 70.8/192.3 MB 3.7 MB/s eta 0:00:34
   -------------- ------------------------- 71.6/192.3 MB 3.7 MB/s eta 0:00:34
   --------------- ------------------------ 72.4/192.3 MB 3.6 MB/s eta 0:00:33
   --------------- ------------------------ 72.9/192.3 MB 3.6 MB/s eta 0:00:33
   --------------- ------------------------ 73.7/192.3 MB 3.6 MB/s eta 0:00:33
   --------------- ------------------------ 74.4/192.3 MB 3.6 MB/s eta 0:00:33
   --------------- ------------------------ 75.2/192.3 MB 3.6 MB/s eta 0:00:33
   --------------- ------------------------ 76.0/192.3 MB 3.6 MB/s eta 0:00:32
   --------------- ------------------------ 76.8/192.3 MB 3.7 MB/s eta 0:00:32
   ---------------- ----------------------- 77.6/192.3 MB 3.6 MB/s eta 0:00:32
   ---------------- ----------------------- 78.4/192.3 MB 3.6 MB/s eta 0:00:32
   ---------------- ----------------------- 78.9/192.3 MB 3.6 MB/s eta 0:00:32
   ---------------- ----------------------- 79.7/192.3 MB 3.6 MB/s eta 0:00:31
   ---------------- ----------------------- 80.2/192.3 MB 3.6 MB/s eta 0:00:31
   ---------------- ----------------------- 80.7/192.3 MB 3.6 MB/s eta 0:00:31
   ---------------- ----------------------- 81.5/192.3 MB 3.6 MB/s eta 0:00:31
   ----------------- ---------------------- 82.3/192.3 MB 3.6 MB/s eta 0:00:31
   ----------------- ---------------------- 83.1/192.3 MB 3.6 MB/s eta 0:00:31
   ----------------- ---------------------- 83.9/192.3 MB 3.6 MB/s eta 0:00:30
   ----------------- ---------------------- 84.7/192.3 MB 3.6 MB/s eta 0:00:30
   ----------------- ---------------------- 85.5/192.3 MB 3.6 MB/s eta 0:00:30
   ----------------- ---------------------- 86.2/192.3 MB 3.6 MB/s eta 0:00:30
   ------------------ --------------------- 87.0/192.3 MB 3.6 MB/s eta 0:00:30
   ------------------ --------------------- 88.1/192.3 MB 3.6 MB/s eta 0:00:29
   ------------------ --------------------- 88.9/192.3 MB 3.6 MB/s eta 0:00:29
   ------------------ --------------------- 89.7/192.3 MB 3.6 MB/s eta 0:00:29
   ------------------ --------------------- 90.2/192.3 MB 3.6 MB/s eta 0:00:29
   ------------------ --------------------- 90.7/192.3 MB 3.6 MB/s eta 0:00:29
   ------------------- -------------------- 91.5/192.3 MB 3.6 MB/s eta 0:00:28
   ------------------- -------------------- 92.0/192.3 MB 3.6 MB/s eta 0:00:28
   ------------------- -------------------- 92.5/192.3 MB 3.6 MB/s eta 0:00:28
   ------------------- -------------------- 93.3/192.3 MB 3.6 MB/s eta 0:00:28
   ------------------- -------------------- 93.8/192.3 MB 3.6 MB/s eta 0:00:28
   ------------------- -------------------- 94.6/192.3 MB 3.6 MB/s eta 0:00:28
   ------------------- -------------------- 95.2/192.3 MB 3.6 MB/s eta 0:00:28
   ------------------- -------------------- 95.7/192.3 MB 3.6 MB/s eta 0:00:28
   -------------------- ------------------- 96.2/192.3 MB 3.6 MB/s eta 0:00:27
   -------------------- ------------------- 97.0/192.3 MB 3.6 MB/s eta 0:00:27
   -------------------- ------------------- 97.5/192.3 MB 3.6 MB/s eta 0:00:27
   -------------------- ------------------- 98.0/192.3 MB 3.6 MB/s eta 0:00:27
   -------------------- ------------------- 98.8/192.3 MB 3.5 MB/s eta 0:00:27
   -------------------- ------------------- 99.4/192.3 MB 3.6 MB/s eta 0:00:27
   -------------------- ------------------- 100.1/192.3 MB 3.5 MB/s eta 0:00:27
   -------------------- ------------------- 100.7/192.3 MB 3.5 MB/s eta 0:00:26
   -------------------- ------------------- 100.9/192.3 MB 3.5 MB/s eta 0:00:26
   --------------------- ------------------ 102.0/192.3 MB 3.5 MB/s eta 0:00:26
   --------------------- ------------------ 102.5/192.3 MB 3.5 MB/s eta 0:00:26
   --------------------- ------------------ 103.0/192.3 MB 3.5 MB/s eta 0:00:26
   --------------------- ------------------ 103.5/192.3 MB 3.5 MB/s eta 0:00:26
   --------------------- ------------------ 104.3/192.3 MB 3.5 MB/s eta 0:00:26
   --------------------- ------------------ 104.9/192.3 MB 3.5 MB/s eta 0:00:25
   --------------------- ------------------ 105.4/192.3 MB 3.5 MB/s eta 0:00:25
   ---------------------- ----------------- 105.9/192.3 MB 3.5 MB/s eta 0:00:25
   ---------------------- ----------------- 106.4/192.3 MB 3.5 MB/s eta 0:00:25
   ---------------------- ----------------- 107.0/192.3 MB 3.5 MB/s eta 0:00:25
   ---------------------- ----------------- 107.7/192.3 MB 3.5 MB/s eta 0:00:25
   ---------------------- ----------------- 108.3/192.3 MB 3.5 MB/s eta 0:00:25
   ---------------------- ----------------- 109.1/192.3 MB 3.4 MB/s eta 0:00:25
   ---------------------- ----------------- 109.6/192.3 MB 3.4 MB/s eta 0:00:25
   ---------------------- ----------------- 110.4/192.3 MB 3.4 MB/s eta 0:00:24
   ----------------------- ---------------- 111.1/192.3 MB 3.4 MB/s eta 0:00:24
   ----------------------- ---------------- 111.7/192.3 MB 3.4 MB/s eta 0:00:24
   ----------------------- ---------------- 112.2/192.3 MB 3.4 MB/s eta 0:00:24
   ----------------------- ---------------- 113.0/192.3 MB 3.4 MB/s eta 0:00:24
   ----------------------- ---------------- 113.5/192.3 MB 3.4 MB/s eta 0:00:24
   ----------------------- ---------------- 114.3/192.3 MB 3.4 MB/s eta 0:00:23
   ----------------------- ---------------- 115.1/192.3 MB 3.4 MB/s eta 0:00:23
   ------------------------ --------------- 115.9/192.3 MB 3.4 MB/s eta 0:00:23
   ------------------------ --------------- 116.4/192.3 MB 3.4 MB/s eta 0:00:23
   ------------------------ --------------- 117.2/192.3 MB 3.4 MB/s eta 0:00:23
   ------------------------ --------------- 117.7/192.3 MB 3.4 MB/s eta 0:00:22
   ------------------------ --------------- 118.2/192.3 MB 3.4 MB/s eta 0:00:22
   ------------------------ --------------- 119.0/192.3 MB 3.4 MB/s eta 0:00:22
   ------------------------ --------------- 119.5/192.3 MB 3.4 MB/s eta 0:00:22
   ------------------------- -------------- 120.3/192.3 MB 3.4 MB/s eta 0:00:22
   ------------------------- -------------- 120.8/192.3 MB 3.4 MB/s eta 0:00:22
   ------------------------- -------------- 121.4/192.3 MB 3.4 MB/s eta 0:00:21
   ------------------------- -------------- 121.9/192.3 MB 3.4 MB/s eta 0:00:21
   ------------------------- -------------- 122.7/192.3 MB 3.4 MB/s eta 0:00:21
   ------------------------- -------------- 123.2/192.3 MB 3.4 MB/s eta 0:00:21
   ------------------------- -------------- 123.7/192.3 MB 3.4 MB/s eta 0:00:21
   ------------------------- -------------- 124.5/192.3 MB 3.4 MB/s eta 0:00:21
   -------------------------- ------------- 125.0/192.3 MB 3.3 MB/s eta 0:00:21
   -------------------------- ------------- 125.8/192.3 MB 3.3 MB/s eta 0:00:20
   -------------------------- ------------- 126.4/192.3 MB 3.3 MB/s eta 0:00:20
   -------------------------- ------------- 126.9/192.3 MB 3.3 MB/s eta 0:00:20
   -------------------------- ------------- 127.7/192.3 MB 3.3 MB/s eta 0:00:20
   -------------------------- ------------- 128.7/192.3 MB 3.3 MB/s eta 0:00:20
   -------------------------- ------------- 129.5/192.3 MB 3.3 MB/s eta 0:00:19
   --------------------------- ------------ 130.3/192.3 MB 3.3 MB/s eta 0:00:19
   --------------------------- ------------ 131.1/192.3 MB 3.3 MB/s eta 0:00:19
   --------------------------- ------------ 131.9/192.3 MB 3.3 MB/s eta 0:00:19
   --------------------------- ------------ 132.6/192.3 MB 3.3 MB/s eta 0:00:18
   --------------------------- ------------ 133.4/192.3 MB 3.3 MB/s eta 0:00:18
   --------------------------- ------------ 134.2/192.3 MB 3.3 MB/s eta 0:00:18
   ---------------------------- ----------- 134.7/192.3 MB 3.3 MB/s eta 0:00:18
   ---------------------------- ----------- 135.5/192.3 MB 3.4 MB/s eta 0:00:17
   ---------------------------- ----------- 136.1/192.3 MB 3.4 MB/s eta 0:00:17
   ---------------------------- ----------- 136.8/192.3 MB 3.4 MB/s eta 0:00:17
   ---------------------------- ----------- 137.4/192.3 MB 3.3 MB/s eta 0:00:17
   ---------------------------- ----------- 138.1/192.3 MB 3.3 MB/s eta 0:00:17
   ---------------------------- ----------- 138.7/192.3 MB 3.3 MB/s eta 0:00:17
   ---------------------------- ----------- 139.2/192.3 MB 3.3 MB/s eta 0:00:16
   ----------------------------- ---------- 140.0/192.3 MB 3.3 MB/s eta 0:00:16
   ----------------------------- ---------- 140.5/192.3 MB 3.3 MB/s eta 0:00:16
   ----------------------------- ---------- 141.3/192.3 MB 3.3 MB/s eta 0:00:16
   ----------------------------- ---------- 142.1/192.3 MB 3.3 MB/s eta 0:00:16
   ----------------------------- ---------- 142.9/192.3 MB 3.3 MB/s eta 0:00:15
   ----------------------------- ---------- 143.7/192.3 MB 3.3 MB/s eta 0:00:15
   ------------------------------ --------- 144.4/192.3 MB 3.3 MB/s eta 0:00:15
   ------------------------------ --------- 145.2/192.3 MB 3.3 MB/s eta 0:00:15
   ------------------------------ --------- 146.0/192.3 MB 3.3 MB/s eta 0:00:15
   ------------------------------ --------- 146.8/192.3 MB 3.3 MB/s eta 0:00:14
   ------------------------------ --------- 147.6/192.3 MB 3.3 MB/s eta 0:00:14
   ------------------------------ --------- 148.6/192.3 MB 3.3 MB/s eta 0:00:14
   ------------------------------- -------- 149.4/192.3 MB 3.3 MB/s eta 0:00:13
   ------------------------------- -------- 150.2/192.3 MB 3.3 MB/s eta 0:00:13
   ------------------------------- -------- 151.0/192.3 MB 3.3 MB/s eta 0:00:13
   ------------------------------- -------- 151.8/192.3 MB 3.3 MB/s eta 0:00:13
   ------------------------------- -------- 152.6/192.3 MB 3.3 MB/s eta 0:00:12
   ------------------------------- -------- 153.4/192.3 MB 3.3 MB/s eta 0:00:12
   -------------------------------- ------- 154.1/192.3 MB 3.3 MB/s eta 0:00:12
   -------------------------------- ------- 155.2/192.3 MB 3.3 MB/s eta 0:00:12
   -------------------------------- ------- 155.7/192.3 MB 3.3 MB/s eta 0:00:11
   -------------------------------- ------- 156.5/192.3 MB 3.3 MB/s eta 0:00:11
   -------------------------------- ------- 157.3/192.3 MB 3.4 MB/s eta 0:00:11
   -------------------------------- ------- 158.1/192.3 MB 3.4 MB/s eta 0:00:11
   --------------------------------- ------ 158.9/192.3 MB 3.3 MB/s eta 0:00:11
   --------------------------------- ------ 159.9/192.3 MB 3.4 MB/s eta 0:00:10
   --------------------------------- ------ 160.7/192.3 MB 3.4 MB/s eta 0:00:10
   --------------------------------- ------ 161.5/192.3 MB 3.4 MB/s eta 0:00:10
   --------------------------------- ------ 162.3/192.3 MB 3.3 MB/s eta 0:00:09
   --------------------------------- ------ 163.1/192.3 MB 3.3 MB/s eta 0:00:09
   ---------------------------------- ----- 163.8/192.3 MB 3.3 MB/s eta 0:00:09
   ---------------------------------- ----- 164.6/192.3 MB 3.3 MB/s eta 0:00:09
   ---------------------------------- ----- 165.4/192.3 MB 3.3 MB/s eta 0:00:09
   ---------------------------------- ----- 166.2/192.3 MB 3.3 MB/s eta 0:00:08
   ---------------------------------- ----- 167.0/192.3 MB 3.3 MB/s eta 0:00:08
   ---------------------------------- ----- 167.8/192.3 MB 3.3 MB/s eta 0:00:08
   ----------------------------------- ---- 168.6/192.3 MB 3.3 MB/s eta 0:00:08
   ----------------------------------- ---- 169.3/192.3 MB 3.3 MB/s eta 0:00:07
   ----------------------------------- ---- 170.1/192.3 MB 3.3 MB/s eta 0:00:07
   ----------------------------------- ---- 170.9/192.3 MB 3.3 MB/s eta 0:00:07

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.23.0 requires torch==2.8.0, but you have torch 2.1.0 which is incompatible.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
!pip install --upgrade torch==2.8.0 torchvision==0.23.0
!pip install --upgrade sentence-transformers protobuf==3.20.3

Collecting torch==2.8.0
  Using cached torch-2.8.0-cp310-cp310-win_amd64.whl.metadata (30 kB)
Requirement already satisfied: torchvision==0.23.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (0.23.0)
Requirement already satisfied: filelock in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.8.0) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.8.0) (4.14.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.8.0) (1.14.0)
Requirement already satisfied: networkx in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.8.0) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.8.0) (3.1.6)
Requirement already satisfied: fsspec in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.8.0) (2025.3.0)
Requirement already satisfied: numpy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torchvision==0.23.0) (2.2.6)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torchvision==0.23.0) (11.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sympy>=1.13.3->torch==2.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch==2.8.0) (3.0.2)
Using cached torch-2.8.0-cp310-cp310-win_amd64.whl (241.4 MB)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0
    Uninstalling torch-2.1.0:
      Successfully uninstalled torch-2.1.0
Successfully installed torch-2.8.0

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: sentence-transformers in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.2.2)
Collecting sentence-transformers
  Using cached sentence_transformers-5.1.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: protobuf==3.20.3 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (3.20.3)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (4.53.3)
Requirement already satisfied: tqdm in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (2.8.0)
Requirement already satisfied: scikit-learn in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.7.0)
Requirement already satisfied: scipy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (0.33.4)
Requirement already satisfied: Pillow in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (4.14.1)
Requirement already satisfied: filelock in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.18.0)
Requirement already satisfied: numpy>=1.17 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.7.14)
Requirement already satisfied: joblib>=1.2.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Using cached sentence_transformers-5.1.0-py3-none-any.whl (483 kB)
Installing collected packages: sentence-transformers
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 2.2.2
    Uninstalling sentence-transformers-2.2.2:
      Successfully uninstalled sentence-transformers-2.2.2
Successfully installed sentence-transformers-5.1.0

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
intent_queries = {
    "TOTAL_SALES": [
        "Show me total sales","What is overall revenue?","How much did we sell in total?",
        "Give me total earnings","Calculate all sales","Sum of all sales","Total revenue please",
        "Overall turnover","Total income of company","Combined sales amount","Gross sales overall",
        "How much revenue did we make?"
    ],
    "TREND_MONTH": [
        "Show monthly sales trend","Sales growth by month","Plot monthly revenue trend",
        "Monthly trend of profits","Month wise performance","Line chart of month sales",
        "Month-to-month sales changes","Which month performed best?"
    ],
    "FILTER_REGION": [
        "Show sales in North region","Sales only for East region","Revenue for South region",
        "Profit in West region","Filter to North zone","East zone revenue","South area sales",
        "West region performance"
    ],
    "AVG_PROFIT_YEAR": [
        "Average profit in 2023","Show average yearly profit","Annual mean profit",
        "Year-wise average earnings","Avg sales in a year","Average revenue per year",
        "Yearly average profit"
    ],
    "AGGREGATE_REGION": [
        "Summarize sales by region","Total sales each region","Group sales by region",
        "Revenue grouped per region","Region wise aggregation of sales","Regional sales totals"
    ],
    "TOP_PRODUCTS": [
        "Top 5 products by sales","Which product sold the most?","Best selling products",
        "Highest revenue items","Popular products list","Top revenue generating items"
    ]
}

# Flatten to DataFrame
rows = []
for intent, qs in intent_queries.items():
    for q in qs:
        rows.append({"query": q, "intent": intent})
train_df = pd.DataFrame(rows)

In [22]:
vectorizer = TfidfVectorizer()
train_texts = train_df["query"].tolist()
train_labels = train_df["intent"].tolist()
train_emb = vectorizer.fit_transform(train_texts)  # sparse TF-IDF matrix

In [23]:
def predict_intent_tfidf(user_query: str, threshold: float = 0.2):
    q_emb = vectorizer.transform([user_query])
    sims = cosine_similarity(train_emb, q_emb).ravel()
    idx = np.argmax(sims)
    best_sim = sims[idx]
    best_intent = train_labels[idx]
    best_example = train_texts[idx]
    
    if best_sim < threshold:
        return None, best_sim, best_example
    return best_intent, best_sim, best_example

In [24]:
tests = [
    "What was our revenue last year?",
    "Give overall sales",
    "Show me region wise totals",
    "Monthly revenue pattern",
    "Best performing items"
]

for t in tests:
    intent, sim, match = predict_intent_tfidf(t, threshold=0.2)
    print(f"Q: {t}\n → intent: {intent} | similarity: {sim:.2f} | matched: {match}\n")

Q: What was our revenue last year?
 → intent: TOTAL_SALES | similarity: 0.54 | matched: What is overall revenue?

Q: Give overall sales
 → intent: TOTAL_SALES | similarity: 0.47 | matched: Gross sales overall

Q: Show me region wise totals
 → intent: TOTAL_SALES | similarity: 0.53 | matched: Show me total sales

Q: Monthly revenue pattern
 → intent: TREND_MONTH | similarity: 0.62 | matched: Plot monthly revenue trend

Q: Best performing items
 → intent: TOP_PRODUCTS | similarity: 0.43 | matched: Highest revenue items

In [31]:
import re
import pandas as pd

def run_intent_on_dataframe(intent, df, user_query=None):
    if intent == "TOTAL_SALES":
        return df["Sales"].sum()
    
    if intent == "TREND_MONTH":
        tmp = df.copy()
        tmp["Month"] = pd.to_datetime(df["Date"]).dt.to_period("M").astype(str)
        
        #detect month/year from query
        if user_query:
            # Detect year like 2024
            year_match = re.search(r"\b(20\d{2})\b", user_query)
            if year_match:
                tmp = tmp[pd.to_datetime(tmp["Date"]).dt.year == int(year_match.group(1))]
        return tmp.groupby("Month")["Sales"].sum().sort_index()
    
    if intent == "FILTER_REGION":
        regions = ["North", "South", "East", "West"]
        if user_query:
            region = next((r for r in regions if r.lower() in user_query.lower()), "East")
        else:
            region = "East"
        return df[df["Region"] == region][["Region","Sales","Profit"]]
    
    if intent == "AVG_PROFIT_YEAR":
        tmp = df.copy()
        tmp["Year"] = pd.to_datetime(df["Date"]).dt.year
        if user_query:
            year_match = re.search(r"\b(20\d{2})\b", user_query)
            if year_match:
                tmp = tmp[tmp["Year"] == int(year_match.group(1))]
        return tmp.groupby("Year")["Profit"].mean()
    
    if intent == "AGGREGATE_REGION":
        return df.groupby("Region")["Sales"].sum().sort_values(ascending=False)
    
    if intent == "TOP_PRODUCTS":
        tmp = df.groupby("Product")["Sales"].sum().sort_values(ascending=False)
        if user_query:
            n_match = re.search(r"\btop (\d+)\b", user_query.lower())
            if n_match:
                n = int(n_match.group(1))
                return tmp.head(n)
        return tmp.head(5)
    
    return "Intent not mapped yet."

In [27]:
import pandas as pd
df = pd.read_excel("sales_data.xlsx")  


df.head()

                     Date Region  Sales  Profit  Product
0 2024-05-20 08:48:58.776   East   1576     389   Tablet
1 2024-04-13 10:17:08.571   West   4493     847   Laptop
2 2024-02-21 17:08:34.286  South    879     380   Mobile
3 2024-06-04 03:25:42.857  South    992     689   Mobile
4 2024-01-26 20:34:17.143  North   2562     555  Monitor

In [32]:
user_query = "Show sales in North region"

# Use your TF-IDF intent prediction
intent, sim, match = predict_intent_tfidf(user_query, threshold=0.20)

if intent is None:
    print("I didn’t understand, please rephrase.")
else:
    print(f"Intent: {intent} (sim {sim:.2f}, matched: '{match}')")
    result = run_intent_on_dataframe(intent, df)
    display(result)

Intent: FILTER_REGION (sim 1.00, matched: 'Show sales in North region')

   Region  Sales  Profit
0    East   1576     389
8    East   2527     239
13   East   4061     682
25   East   4340     868
42   East   3814     559
45   East   3229     436
47   East   3560     662

In [34]:
result = run_intent_on_dataframe(intent, df, user_query=user_query)
display(result)

   Region  Sales  Profit
4   North   2562     555
6   North    564     522
10  North   1995     434
11  North    891     426
26  North   1528     283
35  North   1063     741
37  North   2257     879
40  North   1559     613
49  North   4127     130

In [35]:
user_query = "Give me total sales"
intent, sim, match = predict_intent_tfidf(user_query, threshold=0.50)

if intent is None:
    print("I didn’t understand, please rephrase.")
else:
    print(f"Intent: {intent} (sim {sim:.2f}, matched: '{match}')")
    result = run_intent_on_dataframe(intent, df, user_query)
    print("Result:\n", result)

Intent: TOTAL_SALES (sim 0.82, matched: 'Give me total earnings')
Result:
 137087

In [36]:
user_query = "Show monthly sales trend"
intent, sim, match = predict_intent_tfidf(user_query, threshold=0.50)

if intent is not None:
    result = run_intent_on_dataframe(intent, df, user_query)
    print("Monthly Trend:\n", result)

Monthly Trend:
 Month
2024-01    27577
2024-02    17159
2024-03    34338
2024-04    20086
2024-05    21104
2024-06    16823
Name: Sales, dtype: int64

In [37]:
user_query = "Show average yearly profit"
intent, sim, match = predict_intent_tfidf(user_query, threshold=0.50)

if intent is not None:
    result = run_intent_on_dataframe(intent, df, user_query)
    print("Average Profit per Year:\n", result)

Average Profit per Year:
 Year
2024    523.24
Name: Profit, dtype: float64

In [38]:
user_query = "Summarize sales by region"
intent, sim, match = predict_intent_tfidf(user_query, threshold=0.50)

if intent is not None:
    result = run_intent_on_dataframe(intent, df, user_query)
    print("Sales by Region:\n", result)

Sales by Region:
 Region
West     58718
South    38716
East     23107
North    16546
Name: Sales, dtype: int64

In [39]:
user_query = "Top 5 products by sales"
intent, sim, match = predict_intent_tfidf(user_query, threshold=0.50)

if intent is not None:
    result = run_intent_on_dataframe(intent, df, user_query)
    print("Top Products:\n", result)

Top Products:
 Product
Monitor       36282
Mobile        29364
Tablet        29013
Laptop        28105
Headphones    14323
Name: Sales, dtype: int64